version: '3'
networks:
  registry-net-dev:
    driver: bridge
services: 
  registry:
      container_name: goregistry
      build: .
      ports: 
        -  4500:4500
      command: bash -c "npm start"
      networks: 
        - registry-net-dev
  
  redis-persistance:
       container_name: redis-server
       image: 'bitnami/redis:latest'
       environment:
         - ALLOW_EMPTY_PASSWORD=yes
       ports:
         - "6379:6379"
       networks: 
        - registry-net-dev